import type { Restaurant, Category, Dish } from "@/types";

const UNS = "https://images.unsplash.com/photo-";
const fmt = "?w=800&q=90&auto=format&fit=crop";

export const mockRestaurant: Restaurant = {
  id: "rest-001",
  slug: "casa-do-mar",
  name: "Casa do Mar",
  description:
    "Cozinha mediterrânica contemporânea com ingredientes frescos da costa portuguesa.",
  logo_url: undefined,
  cover_url: `${UNS}1414235077428-338989a2e8c0${fmt}`,
  address: "Rua do Ouro 12, Lisboa",
  phone: "+351 21 000 0000",
  cuisine_type: "Mediterrânica",
  primary_color: "#e6a81e",
  owner_id: "owner-001",
  is_active: true,
  created_at: new Date().toISOString(),
};

export const mockCategories: Category[] = [
  { id: "cat-001", restaurant_id: "rest-001", name: "Entradas",         description: "Para começar bem",            position: 1, created_at: new Date().toISOString() },
  { id: "cat-002", restaurant_id: "rest-001", name: "Pratos Principais",description: "O coração da nossa cozinha",   position: 2, created_at: new Date().toISOString() },
  { id: "cat-003", restaurant_id: "rest-001", name: "Sobremesas",        description: "O final perfeito",            position: 3, created_at: new Date().toISOString() },
  { id: "cat-004", restaurant_id: "rest-001", name: "Vinhos",            description: "Seleção de vinhos portugueses",position: 4, created_at: new Date().toISOString() },
  { id: "cat-005", restaurant_id: "rest-001", name: "Bebidas",           description: "Cervejas, cocktails e sumos", position: 5, created_at: new Date().toISOString() },
];

export const mockDishes: Dish[] = [
  // — Entradas —
  {
    id: "dish-001",
    restaurant_id: "rest-001",
    category_id: "cat-001",
    name: "Polvo à Lagareiro",
    description: "Polvo assado no forno com azeite extra virgem, alho confitado e batata a murro com ervas aromáticas.",
    price: 14.5,
    image_url: `${UNS}1540189549336-e6e99c3679fe${fmt}`,
    allergens: ["moluscos"],
    calories: 320, proteins: 28, carbs: 18, fat: 14,
    is_available: true, is_featured: true,
    tags: ["popular", "sem-glúten"],
    position: 1, created_at: new Date().toISOString(), updated_at: new Date().toISOString(),
  },
  {
    id: "dish-002",
    restaurant_id: "rest-001",
    category_id: "cat-001",
    name: "Alheira de Caça com Ovo",
    description: "Alheira tradicional transmontana grelhada, servida com ovo escalfado e legumes salteados.",
    price: 10.5,
    image_url: `${UNS}1482049016688-2d3e1b311543${fmt}`,
    allergens: ["gluten", "ovos"],
    calories: 480, proteins: 22, carbs: 32, fat: 28,
    is_available: true, is_featured: false,
    tags: [],
    position: 2, created_at: new Date().toISOString(), updated_at: new Date().toISOString(),
  },
  {
    id: "dish-003",
    restaurant_id: "rest-001",
    category_id: "cat-001",
    name: "Creme de Mariscos",
    description: "Sopa cremosa de mariscos com natas, açafrão e torradas de pão de milho.",
    price: 9.0,
    image_url: `${UNS}1547592166-23ac45744acd${fmt}`,
    allergens: ["crustaceos", "moluscos", "leite", "gluten"],
    calories: 380, proteins: 18, carbs: 22, fat: 24,
    is_available: true, is_featured: false,
    tags: [],
    position: 3, created_at: new Date().toISOString(), updated_at: new Date().toISOString(),
  },
  // — Pratos Principais —
  {
    id: "dish-004",
    restaurant_id: "rest-001",
    category_id: "cat-002",
    name: "Bacalhau à Brás",
    description: "Bacalhau desfiado com ovos mexidos, batata palha frita, azeitonas pretas e salsa fresca.",
    price: 22.0,
    image_url: `${UNS}1764333580740-b327847301b1${fmt}`,
    allergens: ["peixe", "ovos"],
    calories: 620, proteins: 42, carbs: 38, fat: 32,
    is_available: true, is_featured: false,
    tags: ["popular", "tradicional"],
    position: 1, created_at: new Date().toISOString(), updated_at: new Date().toISOString(),
  },
  {
    id: "dish-005",
    restaurant_id: "rest-001",
    category_id: "cat-002",
    name: "Robalo Grelhado",
    description: "Robalo inteiro do Atlântico grelhado com limão, azeite aromatizado e legumes da época.",
    price: 28.0,
    image_url: `${UNS}1519708227418-c8fd9a32b7a2${fmt}`,
    allergens: ["peixe"],
    calories: 520, proteins: 52, carbs: 8, fat: 28,
    is_available: true, is_featured: true,
    tags: ["saudável", "sem-glúten"],
    position: 2, created_at: new Date().toISOString(), updated_at: new Date().toISOString(),
  },
  {
    id: "dish-006",
    restaurant_id: "rest-001",
    category_id: "cat-002",
    name: "Secretos de Porco Preto",
    description: "Secretos de porco preto alentejano grelhados a carvão com migas de pão e cogumelos selvagens.",
    price: 24.0,
    image_url: `${UNS}1600891964092-4316c288032e${fmt}`,
    allergens: ["gluten"],
    calories: 680, proteins: 48, carbs: 28, fat: 38,
    is_available: true, is_featured: false,
    tags: ["sem-lactose"],
    position: 3, created_at: new Date().toISOString(), updated_at: new Date().toISOString(),
  },
  {
    id: "dish-007",
    restaurant_id: "rest-001",
    category_id: "cat-002",
    name: "Risotto de Gambas",
    description: "Risotto cremoso com gambas salteadas, parmesão, vinho branco e manjericão fresco.",
    price: 19.5,
    image_url: `${UNS}1476124369491-e7addf5db371${fmt}`,
    allergens: ["crustaceos", "leite", "gluten"],
    calories: 580, proteins: 32, carbs: 58, fat: 22,
    is_available: true, is_featured: false,
    tags: [],
    position: 4, created_at: new Date().toISOString(), updated_at: new Date().toISOString(),
  },
  // — Sobremesas —
  {
    id: "dish-008",
    restaurant_id: "rest-001",
    category_id: "cat-003",
    name: "Pastel de Nata da Casa",
    description: "Pastel de nata artesanal com creme de baunilha, canela e açúcar em pó.",
    price: 4.5,
    image_url: `${UNS}1621303837174-89787a7d4729${fmt}`,
    allergens: ["gluten", "ovos", "leite"],
    calories: 285, proteins: 6, carbs: 38, fat: 12,
    is_available: true, is_featured: true,
    tags: ["popular"],
    position: 1, created_at: new Date().toISOString(), updated_at: new Date().toISOString(),
  },
  {
    id: "dish-009",
    restaurant_id: "rest-001",
    category_id: "cat-003",
    name: "Tarte de Amêndoa",
    description: "Tarte alentejana de amêndoa caramelizada com gelado de mel e lavanda.",
    price: 7.5,
    image_url: `${UNS}1519915028121-7d3463d20b13${fmt}`,
    allergens: ["gluten", "ovos", "leite", "frutos_casca"],
    calories: 420, proteins: 8, carbs: 52, fat: 22,
    is_available: true, is_featured: false,
    tags: [],
    position: 2, created_at: new Date().toISOString(), updated_at: new Date().toISOString(),
  },
  {
    id: "dish-010",
    restaurant_id: "rest-001",
    category_id: "cat-003",
    name: "Mousse de Chocolate Negro",
    description: "Mousse de chocolate negro 70% com flor de sal, praliné de avelã e folha de ouro.",
    price: 8.0,
    image_url: `${UNS}1571877227200-a0d98ea607e9${fmt}`,
    allergens: ["ovos", "leite", "frutos_casca"],
    calories: 380, proteins: 5, carbs: 42, fat: 24,
    is_available: true, is_featured: false,
    tags: ["sem-glúten"],
    position: 3, created_at: new Date().toISOString(), updated_at: new Date().toISOString(),
  },

  // — Vinhos —
  {
    id: "dish-011",
    restaurant_id: "rest-001",
    category_id: "cat-004",
    name: "Quinta do Crasto Reserva Tinto",
    description: "Douro DOC 2021. Lote de Touriga Nacional e Touriga Franca com estágio em carvalho francês. Notas de frutos negros, especiarias e tosta.",
    price: 38.0,
    image_url: `${UNS}1553361371-9b22f78e8b1d${fmt}`,
    allergens: ["sulfitos"],
    calories: undefined, proteins: undefined, carbs: undefined, fat: undefined,
    is_available: true, is_featured: true,
    tags: ["tinto", "Douro"],
    position: 1, created_at: new Date().toISOString(), updated_at: new Date().toISOString(),
  },
  {
    id: "dish-012",
    restaurant_id: "rest-001",
    category_id: "cat-004",
    name: "Anselmo Mendes Alvarinho",
    description: "Vinho Verde DOC 2023. Alvarinho a 100% das encostas de Monção. Fresco, cítrico, com acidez vibrante e final mineral.",
    price: 28.0,
    image_url: `${UNS}1682071308366-1d098905b498${fmt}`,
    allergens: ["sulfitos"],
    calories: undefined, proteins: undefined, carbs: undefined, fat: undefined,
    is_available: true, is_featured: false,
    tags: ["branco", "Vinho Verde"],
    position: 2, created_at: new Date().toISOString(), updated_at: new Date().toISOString(),
  },
  {
    id: "dish-013",
    restaurant_id: "rest-001",
    category_id: "cat-004",
    name: "Esporão Reserva Branco",
    description: "Alentejo DOC 2022. Blend de Antão Vaz e Arinto com fermentação parcial em barrica. Cremoso, com notas de frutos tropicais e baunilha.",
    price: 32.0,
    image_url: `${UNS}1474506654191-f7d09ec90b52${fmt}`,
    allergens: ["sulfitos"],
    calories: undefined, proteins: undefined, carbs: undefined, fat: undefined,
    is_available: true, is_featured: false,
    tags: ["branco", "Alentejo"],
    position: 3, created_at: new Date().toISOString(), updated_at: new Date().toISOString(),
  },
  {
    id: "dish-014",
    restaurant_id: "rest-001",
    category_id: "cat-004",
    name: "Niepoort Nat'Cool Rosé",
    description: "Douro 2023. Rosé leve e refrescante, cor salmão, aromas de framboesa e flor de rosa. Perfeito para os meses quentes.",
    price: 24.0,
    image_url: `${UNS}1622119396095-378684e4bfa8${fmt}`,
    allergens: ["sulfitos"],
    calories: undefined, proteins: undefined, carbs: undefined, fat: undefined,
    is_available: true, is_featured: false,
    tags: ["rosé", "Douro"],
    position: 4, created_at: new Date().toISOString(), updated_at: new Date().toISOString(),
  },

  // — Bebidas —
  {
    id: "dish-015",
    restaurant_id: "rest-001",
    category_id: "cat-005",
    name: "Gin Tónico da Casa",
    description: "Gin Hendrick's com tónica premium Fever-Tree, pepino, zimbro e rodela de limão. Servido em copo de balão com gelo.",
    price: 12.0,
    image_url: `${UNS}1563227812-0ea4c22e6cc8${fmt}`,
    allergens: [],
    calories: 180, proteins: 0, carbs: 14, fat: 0,
    is_available: true, is_featured: false,
    tags: ["cocktail", "com álcool"],
    position: 1, created_at: new Date().toISOString(), updated_at: new Date().toISOString(),
  },
  {
    id: "dish-016",
    restaurant_id: "rest-001",
    category_id: "cat-005",
    name: "Aperol Spritz",
    description: "Aperol, Prosecco DOC e água com gás com fatia de laranja. O clássico aperitivo italiano refrescante.",
    price: 10.0,
    image_url: `${UNS}1585975776023-29a0dbc51407${fmt}`,
    allergens: ["sulfitos"],
    calories: 160, proteins: 0, carbs: 18, fat: 0,
    is_available: true, is_featured: false,
    tags: ["cocktail", "com álcool"],
    position: 2, created_at: new Date().toISOString(), updated_at: new Date().toISOString(),
  },
  {
    id: "dish-017",
    restaurant_id: "rest-001",
    category_id: "cat-005",
    name: "Cerveja Artesanal IPA",
    description: "IPA nacional produzida em Lisboa. Lúpulo intenso, aromas cítricos e final amargo equilibrado. 5.8% vol.",
    price: 5.5,
    image_url: `${UNS}1437418747212-8d9709afab22${fmt}`,
    allergens: ["gluten"],
    calories: 210, proteins: 2, carbs: 18, fat: 0,
    is_available: true, is_featured: false,
    tags: ["cerveja", "com álcool"],
    position: 3, created_at: new Date().toISOString(), updated_at: new Date().toISOString(),
  },
  {
    id: "dish-018",
    restaurant_id: "rest-001",
    category_id: "cat-005",
    name: "Limonada Fresca da Casa",
    description: "Limão espremido na hora, hortelã fresca, xarope de açúcar artesanal e água com gás. Refrescante e natural.",
    price: 4.5,
    image_url: `${UNS}1513558161293-cdaf765ed2fd${fmt}`,
    allergens: [],
    calories: 95, proteins: 0, carbs: 22, fat: 0,
    is_available: true, is_featured: false,
    tags: ["sem álcool"],
    position: 4, created_at: new Date().toISOString(), updated_at: new Date().toISOString(),
  },
  {
    id: "dish-019",
    restaurant_id: "rest-001",
    category_id: "cat-005",
    name: "Água com Gás Pedras",
    description: "Água mineral natural com gás Pedras Salgadas, 75cl. A água gasificada mais icónica de Portugal.",
    price: 3.0,
    image_url: `${UNS}1705413085032-77fec96871cf${fmt}`,
    allergens: [],
    calories: 0, proteins: 0, carbs: 0, fat: 0,
    is_available: true, is_featured: false,
    tags: ["sem álcool"],
    position: 5, created_at: new Date().toISOString(), updated_at: new Date().toISOString(),
  },
  {
    id: "dish-020",
    restaurant_id: "rest-001",
    category_id: "cat-005",
    name: "Espresso Duplo",
    description: "Blend exclusivo de grãos de origem única, tostagem média-escura. Servido com petit four da casa.",
    price: 2.5,
    image_url: `${UNS}1544145945-f90425340c7e${fmt}`,
    allergens: [],
    calories: 5, proteins: 0, carbs: 1, fat: 0,
    is_available: true, is_featured: false,
    tags: ["café", "sem álcool"],
    position: 6, created_at: new Date().toISOString(), updated_at: new Date().toISOString(),
  },
];
