import type { Restaurant, Category, Dish } from "@/types";

const UNS = "https://images.unsplash.com/photo-";
const fmt = "?w=800&q=90&auto=format&fit=crop";

export const mockRestaurant: Restaurant = {
  id: "rest-001",
  slug: "casa-do-mar",
  name: "Casa do Mar",
  description:
    "Onde o mar encontra a mesa. Cozinha atlântica contemporânea feita com o que a costa nos oferece.",
  review_url: "https://g.page/r/CasaDoMarLisboa/review",
  logo_url: undefined,
  cover_url: `${UNS}1414235077428-338989a2e8c0${fmt}`,
  address: "Rua do Ouro 12, Lisboa",
  phone: "+351 21 000 0000",
  cuisine_type: "Mediterrânica",
  primary_color: "#e6a81e",
  owner_id: "owner-001",
  is_active: true,
  created_at: new Date().toISOString(),
};

export const mockCategories: Category[] = [
  {
    id: "cat-001", restaurant_id: "rest-001", name: "Entradas", description: "Para começar bem", position: 1, created_at: new Date().toISOString(),
    translations: {
      en: { name: "Starters", description: "The perfect start" },
      es: { name: "Entrantes", description: "El comienzo perfecto" },
      fr: { name: "Entrées", description: "Pour bien commencer" },
    },
  },
  {
    id: "cat-002", restaurant_id: "rest-001", name: "Pratos Principais", description: "O coração da nossa cozinha", position: 2, created_at: new Date().toISOString(),
    translations: {
      en: { name: "Main Courses", description: "The heart of our kitchen" },
      es: { name: "Platos Principales", description: "El corazón de nuestra cocina" },
      fr: { name: "Plats Principaux", description: "Le cœur de notre cuisine" },
    },
  },
  {
    id: "cat-003", restaurant_id: "rest-001", name: "Sobremesas", description: "O final perfeito", position: 3, created_at: new Date().toISOString(),
    translations: {
      en: { name: "Desserts", description: "The perfect ending" },
      es: { name: "Postres", description: "El final perfecto" },
      fr: { name: "Desserts", description: "La conclusion parfaite" },
    },
  },
  {
    id: "cat-004", restaurant_id: "rest-001", name: "Vinhos", description: "Seleção de vinhos portugueses", position: 4, created_at: new Date().toISOString(),
    translations: {
      en: { name: "Wines", description: "Selection of Portuguese wines" },
      es: { name: "Vinos", description: "Selección de vinos portugueses" },
      fr: { name: "Vins", description: "Sélection de vins portugais" },
    },
  },
  {
    id: "cat-005", restaurant_id: "rest-001", name: "Bebidas", description: "Cervejas, cocktails e sumos", position: 5, created_at: new Date().toISOString(),
    translations: {
      en: { name: "Beverages", description: "Beers, cocktails and juices" },
      es: { name: "Bebidas", description: "Cervezas, cócteles y zumos" },
      fr: { name: "Boissons", description: "Bières, cocktails et jus" },
    },
  },
];

export const mockDishes: Dish[] = [
  // — Entradas —
  {
    id: "dish-001", restaurant_id: "rest-001", category_id: "cat-001",
    name: "Polvo à Lagareiro",
    description: "Do fundo do Atlântico para a sua mesa: tentáculos dourados no forno, banhados em azeite extra virgem e alho confitado. Batata a murro que guarda ainda o sabor da brisa da costa.",
    translations: {
      en: { name: "Octopus à Lagareiro", description: "From the Atlantic depths to your table: golden oven-roasted tentacles bathed in extra virgin olive oil and confit garlic. Crushed potatoes still carrying the scent of the sea breeze." },
      es: { name: "Pulpo à Lagareiro", description: "Desde las profundidades del Atlántico hasta tu mesa: tentáculos dorados al horno bañados en aceite de oliva virgen extra y ajo confitado. Patatas machacadas con el sabor de la brisa costera." },
      fr: { name: "Pieuvre à Lagareiro", description: "Des profondeurs de l'Atlantique à votre table : tentacules dorés au four, baignés d'huile d'olive extra vierge et d'ail confit. Pommes de terre écrasées imprégnées de la brise marine." },
    },
    price: 14.5, image_url: `${UNS}1540189549336-e6e99c3679fe${fmt}`,
    allergens: ["moluscos"], calories: 320, proteins: 28, carbs: 18, fat: 14,
    is_available: true, is_featured: true, tags: ["popular", "sem-glúten"],
    position: 1, created_at: new Date().toISOString(), updated_at: new Date().toISOString(),
  },
  {
    id: "dish-002", restaurant_id: "rest-001", category_id: "cat-001",
    name: "Alheira de Caça com Ovo",
    description: "Alheira transmontana grelhada lentamente até estalar, coroada com ovo escalfado como a lua sobre o rio. A tradição das serras em diálogo com a frescura da costa.",
    translations: {
      en: { name: "Game Sausage with Egg", description: "Traditional Transmontana game sausage grilled until it crackles, crowned with a poached egg like the moon over the river. Mountain tradition in dialogue with coastal freshness." },
      es: { name: "Alheira de Caza con Huevo", description: "Alheira transmontana a la plancha hasta que cruje, coronada con huevo escalfado como la luna sobre el río. Tradición serrana en diálogo con la frescura costera." },
      fr: { name: "Saucisse de Gibier à l'Oeuf", description: "Alheira transmontane grillée jusqu'à ce qu'elle crépite, couronnée d'un oeuf poché comme la lune sur la rivière. Tradition montagnarde en dialogue avec la fraîcheur côtière." },
    },
    price: 10.5, image_url: `${UNS}1482049016688-2d3e1b311543${fmt}`,
    allergens: ["gluten", "ovos"], calories: 480, proteins: 22, carbs: 32, fat: 28,
    is_available: true, is_featured: false, tags: [],
    position: 2, created_at: new Date().toISOString(), updated_at: new Date().toISOString(),
  },
  {
    id: "dish-003", restaurant_id: "rest-001", category_id: "cat-001",
    name: "Creme de Mariscos",
    description: "O oceano em forma de sopa: marisco fresco da costa transformado num creme aveludado com açafrão da terra e natas. Servido com torradas crocantes de pão de milho que absorvem o mar.",
    translations: {
      en: { name: "Seafood Bisque", description: "The ocean in soup form: fresh coastal seafood transformed into a velvety cream with saffron and cream. Served with crispy cornbread toast that soaks up the sea." },
      es: { name: "Crema de Mariscos", description: "El océano en forma de sopa: marisco fresco de la costa convertido en una crema aterciopelada con azafrán y nata. Servido con tostadas crujientes de pan de maíz que absorben el mar." },
      fr: { name: "Bisque de Fruits de Mer", description: "L'océan en forme de soupe : fruits de mer frais de la côte transformés en une crème veloutée au safran et à la crème. Servi avec des toasts croustillants de pain de maïs qui absorbent la mer." },
    },
    price: 9.0, image_url: `${UNS}1547592166-23ac45744acd${fmt}`,
    allergens: ["crustaceos", "moluscos", "leite", "gluten"], calories: 380, proteins: 18, carbs: 22, fat: 24,
    is_available: true, is_featured: false, tags: [],
    position: 3, created_at: new Date().toISOString(), updated_at: new Date().toISOString(),
  },
  // — Pratos Principais —
  {
    id: "dish-004", restaurant_id: "rest-001", category_id: "cat-002",
    name: "Bacalhau à Brás",
    description: "O embaixador dos mares frios do Atlântico Norte, desfiado à mão em fios de prata. Salteado em azeite e alho, abraçado por batata palha estaladiça, ovos mexidos e azeitonas. Portugal num prato.",
    translations: {
      en: { name: "Bacalhau à Brás", description: "The ambassador of the cold North Atlantic, hand-shredded into silver threads. Sautéed in olive oil and garlic, embraced by crispy straw potatoes, scrambled eggs and olives. Portugal on a plate." },
      es: { name: "Bacalao à Brás", description: "El embajador de los mares fríos del Atlántico Norte, desmigado a mano en hilos de plata. Salteado en aceite y ajo, abrazado por patatas paja crujientes, huevos revueltos y aceitunas. Portugal en un plato." },
      fr: { name: "Morue à la Brás", description: "L'ambassadeur des mers froides de l'Atlantique Nord, effiloché à la main en fils d'argent. Sauté à l'huile d'olive et à l'ail, enlacé de pommes paille croustillantes, d'oeufs brouillés et d'olives. Le Portugal dans une assiette." },
    },
    price: 22.0, image_url: `${UNS}1764333580740-b327847301b1${fmt}`,
    allergens: ["peixe", "ovos"], calories: 620, proteins: 42, carbs: 38, fat: 32,
    is_available: true, is_featured: true, tags: ["popular", "tradicional"],
    position: 1, created_at: new Date().toISOString(), updated_at: new Date().toISOString(),
  },
  {
    id: "dish-005", restaurant_id: "rest-001", category_id: "cat-002",
    name: "Robalo Grelhado",
    description: "Pescado esta manhã nas águas atlânticas de Cascais, o robalo chega à grelha com a pele prateada. Sai com o coração suculento, banhado em azeite de ervas e limão confitado que cheira ao mar aberto.",
    translations: {
      en: { name: "Grilled Sea Bass", description: "Caught this morning in the Atlantic waters of Cascais, the sea bass reaches the grill with its silver skin. It emerges with a succulent heart, bathed in herb olive oil and confit lemon that smells of the open sea." },
      es: { name: "Lubina a la Plancha", description: "Pescada esta mañana en las aguas atlánticas de Cascais, la lubina llega a la plancha con su piel plateada. Sale con el corazón jugoso, bañada en aceite de hierbas y limón confitado que huele al mar abierto." },
      fr: { name: "Bar Grillé", description: "Pêché ce matin dans les eaux atlantiques de Cascais, le bar arrive sur le grill avec sa peau argentée. Il en ressort avec un cœur juteux, baigné d'huile aux herbes et de citron confit qui sent la mer ouverte." },
    },
    price: 28.0, image_url: `${UNS}1519708227418-c8fd9a32b7a2${fmt}`,
    allergens: ["peixe"], calories: 520, proteins: 52, carbs: 8, fat: 28,
    is_available: true, is_featured: true, tags: ["saudável", "sem-glúten"],
    position: 2, created_at: new Date().toISOString(), updated_at: new Date().toISOString(),
  },
  {
    id: "dish-006", restaurant_id: "rest-001", category_id: "cat-002",
    name: "Secretos de Porco Preto",
    description: "Criado livre sob os sobreiros do Alentejo, o porco preto guarda na sua carne marmoreada o sabor da terra e do carvalho. Na brasa, os secretos revelam-se com migas rústicas de broa e cogumelos selvagens.",
    translations: {
      en: { name: "Black Pork Secreto", description: "Raised free under the cork oaks of Alentejo, the black pork stores in its marbled meat the flavour of the land and oak. On the charcoal, the secreto cuts reveal themselves with rustic cornbread crumbs and wild mushrooms." },
      es: { name: "Secretos de Cerdo Negro", description: "Criado libre bajo los alcornoques del Alentejo, el cerdo negro guarda en su carne marmolada el sabor de la tierra y el roble. En las brasas, los secretos se revelan con migas rústicas de broa y setas silvestres." },
      fr: { name: "Secreto de Porc Noir", description: "Élevé en liberté sous les chênes-lièges de l'Alentejo, le porc noir conserve dans sa viande marbrée les saveurs de la terre et du chêne. Sur les braises, les secretos se révèlent avec des migas rustiques de broa et des champignons sauvages." },
    },
    price: 24.0, image_url: `${UNS}1600891964092-4316c288032e${fmt}`,
    allergens: ["gluten"], calories: 680, proteins: 48, carbs: 28, fat: 38,
    is_available: true, is_featured: false, tags: ["sem-lactose"],
    position: 3, created_at: new Date().toISOString(), updated_at: new Date().toISOString(),
  },
  {
    id: "dish-007", restaurant_id: "rest-001", category_id: "cat-002",
    name: "Risotto de Gambas",
    description: "Gambas do Algarve saltadas em manteiga e alho como a maré que sobe, mergulhadas em risotto cremoso de parmesão com fios de vinho branco da costa. O Mediterrâneo encontra o Atlântico num prato.",
    translations: {
      en: { name: "Prawn Risotto", description: "Algarve prawns sautéed in butter and garlic like a rising tide, plunged into creamy parmesan risotto with threads of coastal white wine. The Mediterranean meets the Atlantic in a single plate." },
      es: { name: "Risotto de Gambas", description: "Gambas del Algarve salteadas en mantequilla y ajo como la marea que sube, sumergidas en risotto cremoso de parmesano con hilos de vino blanco costero. El Mediterráneo se encuentra con el Atlántico en un plato." },
      fr: { name: "Risotto aux Crevettes", description: "Crevettes de l'Algarve sautées au beurre et à l'ail comme une marée montante, plongées dans un risotto crémeux au parmesan avec des filets de vin blanc côtier. La Méditerranée rencontre l'Atlantique dans une seule assiette." },
    },
    price: 19.5, image_url: `${UNS}1476124369491-e7addf5db371${fmt}`,
    allergens: ["crustaceos", "leite", "gluten"], calories: 580, proteins: 32, carbs: 58, fat: 22,
    is_available: true, is_featured: false, tags: [],
    position: 4, created_at: new Date().toISOString(), updated_at: new Date().toISOString(),
  },
  // — Sobremesas —
  {
    id: "dish-008", restaurant_id: "rest-001", category_id: "cat-003",
    name: "Pastel de Nata da Casa",
    description: "A joia da pastelaria portuguesa feita à mão: massa folhada que estala como a espuma do mar, creme de baunilha da Madeira e uma nuvem de canela. O sabor de Lisboa com o perfume do Atlântico.",
    translations: {
      en: { name: "House Custard Tart", description: "The jewel of Portuguese pastry, handmade: flaky pastry that crackles like sea foam, Madeira vanilla cream and a cloud of cinnamon. The taste of Lisbon with the scent of the Atlantic." },
      es: { name: "Pastel de Nata de la Casa", description: "La joya de la pastelería portuguesa hecha a mano: masa hojaldrada que cruje como la espuma del mar, crema de vainilla de Madeira y una nube de canela. El sabor de Lisboa con el perfume del Atlántico." },
      fr: { name: "Tarte à la Crème Maison", description: "Le joyau de la pâtisserie portugaise, fait à la main : pâte feuilletée qui craque comme l'écume de mer, crème à la vanille de Madère et un nuage de cannelle. Le goût de Lisbonne avec le parfum de l'Atlantique." },
    },
    price: 4.5, image_url: `${UNS}1621303837174-89787a7d4729${fmt}`,
    allergens: ["gluten", "ovos", "leite"], calories: 285, proteins: 6, carbs: 38, fat: 12,
    is_available: true, is_featured: true, tags: ["popular"],
    position: 1, created_at: new Date().toISOString(), updated_at: new Date().toISOString(),
  },
  {
    id: "dish-009", restaurant_id: "rest-001", category_id: "cat-003",
    name: "Tarte de Amêndoa",
    description: "Das amendoeiras alentejanas que florescem em fevereiro como espuma branca sobre o campo: uma tarte caramelizada com gelado artesanal de mel da Serra da Estrela e lavanda selvagem.",
    translations: {
      en: { name: "Almond Tart", description: "From the Alentejo almond trees that bloom in February like white foam over the fields: a caramelised tart with artisan honey ice cream from Serra da Estrela and wild lavender." },
      es: { name: "Tarta de Almendra", description: "De los almendros alentejanos que florecen en febrero como espuma blanca sobre el campo: una tarta caramelizada con helado artesanal de miel de la Serra da Estrela y lavanda silvestre." },
      fr: { name: "Tarte aux Amandes", description: "Des amandiers alentejanos qui fleurissent en février comme de l'écume blanche sur les champs : une tarte caramélisée avec une glace artisanale au miel de la Serra da Estrela et à la lavande sauvage." },
    },
    price: 7.5, image_url: `${UNS}1519915028121-7d3463d20b13${fmt}`,
    allergens: ["gluten", "ovos", "leite", "frutos_casca"], calories: 420, proteins: 8, carbs: 52, fat: 22,
    is_available: true, is_featured: false, tags: [],
    position: 2, created_at: new Date().toISOString(), updated_at: new Date().toISOString(),
  },
  {
    id: "dish-010", restaurant_id: "rest-001", category_id: "cat-003",
    name: "Mousse de Chocolate Negro",
    description: "Chocolate de São Tomé a 70%, batido em nuvem escura como as profundezas do Atlântico. Equilibrado com flor de sal colhida nas salinas de Aveiro, praliné de avelã e o toque final de uma folha de ouro.",
    translations: {
      en: { name: "Dark Chocolate Mousse", description: "São Tomé chocolate at 70%, whipped into a dark cloud like the depths of the Atlantic. Balanced with fleur de sel harvested from the Aveiro salt flats, hazelnut praline and the final touch of a gold leaf." },
      es: { name: "Mousse de Chocolate Negro", description: "Chocolate de São Tomé al 70%, batido en nube oscura como las profundidades del Atlántico. Equilibrado con flor de sal recogida en las salinas de Aveiro, praliné de avellana y el toque final de una hoja de oro." },
      fr: { name: "Mousse au Chocolat Noir", description: "Chocolat de São Tomé à 70%, monté en nuage sombre comme les profondeurs de l'Atlantique. Équilibré avec de la fleur de sel récoltée dans les salines d'Aveiro, pralin noisette et la touche finale d'une feuille d'or." },
    },
    price: 8.0, image_url: `${UNS}1571877227200-a0d98ea607e9${fmt}`,
    allergens: ["ovos", "leite", "frutos_casca"], calories: 380, proteins: 5, carbs: 42, fat: 24,
    is_available: true, is_featured: false, tags: ["sem-glúten"],
    position: 3, created_at: new Date().toISOString(), updated_at: new Date().toISOString(),
  },
  // — Vinhos —
  {
    id: "dish-011", restaurant_id: "rest-001", category_id: "cat-004",
    name: "Quinta do Crasto Reserva Tinto",
    description: "Douro DOC 2021. Lote de Touriga Nacional e Touriga Franca com estágio em carvalho francês. Notas de frutos negros, especiarias e tosta.",
    translations: {
      en: { name: "Quinta do Crasto Reserva Red", description: "Douro DOC 2021. Blend of Touriga Nacional and Touriga Franca aged in French oak. Notes of dark fruit, spices and toast." },
      es: { name: "Quinta do Crasto Reserva Tinto", description: "Douro DOC 2021. Mezcla de Touriga Nacional y Touriga Franca con crianza en roble francés. Notas de frutos negros, especias y tostado." },
      fr: { name: "Quinta do Crasto Reserva Rouge", description: "Douro DOC 2021. Assemblage de Touriga Nacional et Touriga Franca élevé en chêne français. Notes de fruits noirs, épices et toast." },
    },
    price: 38.0, image_url: `${UNS}1553361371-9b22f78e8b1d${fmt}`,
    allergens: ["sulfitos"], calories: undefined, proteins: undefined, carbs: undefined, fat: undefined,
    is_available: true, is_featured: true, tags: ["tinto", "Douro"],
    position: 1, created_at: new Date().toISOString(), updated_at: new Date().toISOString(),
  },
  {
    id: "dish-012", restaurant_id: "rest-001", category_id: "cat-004",
    name: "Anselmo Mendes Alvarinho",
    description: "Vinho Verde DOC 2023. Alvarinho a 100% das encostas de Monção. Fresco, cítrico, com acidez vibrante e final mineral.",
    translations: {
      en: { name: "Anselmo Mendes Alvarinho", description: "Vinho Verde DOC 2023. 100% Alvarinho from the slopes of Monção. Fresh, citrusy, with vibrant acidity and a mineral finish." },
      es: { name: "Anselmo Mendes Alvarinho", description: "Vinho Verde DOC 2023. Alvarinho al 100% de las laderas de Monção. Fresco, cítrico, con acidez vibrante y final mineral." },
      fr: { name: "Anselmo Mendes Alvarinho", description: "Vinho Verde DOC 2023. Alvarinho à 100% des coteaux de Monção. Frais, citronné, avec une acidité vibrante et une finale minérale." },
    },
    price: 28.0, image_url: `${UNS}1682071308366-1d098905b498${fmt}`,
    allergens: ["sulfitos"], calories: undefined, proteins: undefined, carbs: undefined, fat: undefined,
    is_available: true, is_featured: false, tags: ["branco", "Vinho Verde"],
    position: 2, created_at: new Date().toISOString(), updated_at: new Date().toISOString(),
  },
  {
    id: "dish-013", restaurant_id: "rest-001", category_id: "cat-004",
    name: "Esporão Reserva Branco",
    description: "Alentejo DOC 2022. Blend de Antão Vaz e Arinto com fermentação parcial em barrica. Cremoso, com notas de frutos tropicais e baunilha.",
    translations: {
      en: { name: "Esporão Reserva White", description: "Alentejo DOC 2022. Blend of Antão Vaz and Arinto with partial barrel fermentation. Creamy, with notes of tropical fruits and vanilla." },
      es: { name: "Esporão Reserva Blanco", description: "Alentejo DOC 2022. Mezcla de Antão Vaz y Arinto con fermentación parcial en barrica. Cremoso, con notas de frutas tropicales y vainilla." },
      fr: { name: "Esporão Reserva Blanc", description: "Alentejo DOC 2022. Assemblage d'Antão Vaz et Arinto avec fermentation partielle en barrique. Crémeux, avec des notes de fruits tropicaux et vanille." },
    },
    price: 32.0, image_url: `${UNS}1474506654191-f7d09ec90b52${fmt}`,
    allergens: ["sulfitos"], calories: undefined, proteins: undefined, carbs: undefined, fat: undefined,
    is_available: true, is_featured: false, tags: ["branco", "Alentejo"],
    position: 3, created_at: new Date().toISOString(), updated_at: new Date().toISOString(),
  },
  {
    id: "dish-014", restaurant_id: "rest-001", category_id: "cat-004",
    name: "Niepoort Nat'Cool Rosé",
    description: "Douro 2023. Rosé leve e refrescante, cor salmão, aromas de framboesa e flor de rosa. Perfeito para os meses quentes.",
    translations: {
      en: { name: "Niepoort Nat'Cool Rosé", description: "Douro 2023. Light and refreshing rosé, salmon colour, aromas of raspberry and rose blossom. Perfect for warm months." },
      es: { name: "Niepoort Nat'Cool Rosado", description: "Douro 2023. Rosado ligero y refrescante, color salmón, aromas de frambuesa y flor de rosa. Perfecto para los meses cálidos." },
      fr: { name: "Niepoort Nat'Cool Rosé", description: "Douro 2023. Rosé léger et rafraîchissant, couleur saumon, arômes de framboise et de fleur de rose. Parfait pour les mois chauds." },
    },
    price: 24.0, image_url: `${UNS}1622119396095-378684e4bfa8${fmt}`,
    allergens: ["sulfitos"], calories: undefined, proteins: undefined, carbs: undefined, fat: undefined,
    is_available: true, is_featured: false, tags: ["rosé", "Douro"],
    position: 4, created_at: new Date().toISOString(), updated_at: new Date().toISOString(),
  },
  // — Bebidas —
  {
    id: "dish-015", restaurant_id: "rest-001", category_id: "cat-005",
    name: "Gin Tónico da Casa",
    description: "Gin Hendrick's com tónica premium Fever-Tree, pepino, zimbro e rodela de limão. Servido em copo de balão com gelo.",
    translations: {
      en: { name: "House Gin & Tonic", description: "Hendrick's Gin with premium Fever-Tree tonic, cucumber, juniper and a lemon slice. Served in a balloon glass with ice." },
      es: { name: "Gin Tónico de la Casa", description: "Gin Hendrick's con tónica premium Fever-Tree, pepino, enebro y rodaja de limón. Servido en copa globo con hielo." },
      fr: { name: "Gin Tonic Maison", description: "Gin Hendrick's avec tonic premium Fever-Tree, concombre, genièvre et rondelle de citron. Servi dans un verre ballon avec glace." },
    },
    price: 12.0, image_url: `${UNS}1563227812-0ea4c22e6cc8${fmt}`,
    allergens: [], calories: 180, proteins: 0, carbs: 14, fat: 0,
    is_available: true, is_featured: false, tags: ["cocktail", "com álcool"],
    position: 1, created_at: new Date().toISOString(), updated_at: new Date().toISOString(),
  },
  {
    id: "dish-016", restaurant_id: "rest-001", category_id: "cat-005",
    name: "Aperol Spritz",
    description: "Aperol, Prosecco DOC e água com gás com fatia de laranja. O clássico aperitivo italiano refrescante.",
    translations: {
      en: { name: "Aperol Spritz", description: "Aperol, Prosecco DOC and sparkling water with a slice of orange. The classic refreshing Italian aperitif." },
      es: { name: "Aperol Spritz", description: "Aperol, Prosecco DOC y agua con gas con rodaja de naranja. El clásico aperitivo italiano refrescante." },
      fr: { name: "Aperol Spritz", description: "Aperol, Prosecco DOC et eau gazeuse avec une tranche d'orange. Le classique apéritif italien rafraîchissant." },
    },
    price: 10.0, image_url: `${UNS}1585975776023-29a0dbc51407${fmt}`,
    allergens: ["sulfitos"], calories: 160, proteins: 0, carbs: 18, fat: 0,
    is_available: true, is_featured: false, tags: ["cocktail", "com álcool"],
    position: 2, created_at: new Date().toISOString(), updated_at: new Date().toISOString(),
  },
  {
    id: "dish-017", restaurant_id: "rest-001", category_id: "cat-005",
    name: "Cerveja Artesanal IPA",
    description: "IPA nacional produzida em Lisboa. Lúpulo intenso, aromas cítricos e final amargo equilibrado. 5.8% vol.",
    translations: {
      en: { name: "Craft IPA Beer", description: "National IPA brewed in Lisbon. Intense hops, citrus aromas and a balanced bitter finish. 5.8% vol." },
      es: { name: "Cerveza Artesanal IPA", description: "IPA nacional elaborada en Lisboa. Lúpulo intenso, aromas cítricos y final amargo equilibrado. 5.8% vol." },
      fr: { name: "Bière Artisanale IPA", description: "IPA nationale brassée à Lisbonne. Houblon intense, arômes citronnés et finale amère équilibrée. 5,8% vol." },
    },
    price: 5.5, image_url: `${UNS}1437418747212-8d9709afab22${fmt}`,
    allergens: ["gluten"], calories: 210, proteins: 2, carbs: 18, fat: 0,
    is_available: true, is_featured: false, tags: ["cerveja", "com álcool"],
    position: 3, created_at: new Date().toISOString(), updated_at: new Date().toISOString(),
  },
  {
    id: "dish-018", restaurant_id: "rest-001", category_id: "cat-005",
    name: "Limonada Fresca da Casa",
    description: "Limão espremido na hora, hortelã fresca, xarope de açúcar artesanal e água com gás. Refrescante e natural.",
    translations: {
      en: { name: "House Fresh Lemonade", description: "Freshly squeezed lemon, fresh mint, artisan sugar syrup and sparkling water. Refreshing and natural." },
      es: { name: "Limonada Fresca de la Casa", description: "Limón exprimido al momento, menta fresca, sirope de azúcar artesanal y agua con gas. Refrescante y natural." },
      fr: { name: "Limonade Fraîche Maison", description: "Citron pressé frais, menthe fraîche, sirop de sucre artisanal et eau gazeuse. Rafraîchissant et naturel." },
    },
    price: 4.5, image_url: `${UNS}1513558161293-cdaf765ed2fd${fmt}`,
    allergens: [], calories: 95, proteins: 0, carbs: 22, fat: 0,
    is_available: true, is_featured: false, tags: ["sem álcool"],
    position: 4, created_at: new Date().toISOString(), updated_at: new Date().toISOString(),
  },
  {
    id: "dish-019", restaurant_id: "rest-001", category_id: "cat-005",
    name: "Água com Gás Pedras",
    description: "Água mineral natural com gás Pedras Salgadas, 75cl. A água gasificada mais icónica de Portugal.",
    translations: {
      en: { name: "Pedras Sparkling Water", description: "Pedras Salgadas natural sparkling mineral water, 75cl. Portugal's most iconic sparkling water." },
      es: { name: "Agua con Gas Pedras", description: "Agua mineral natural con gas Pedras Salgadas, 75cl. El agua con gas más icónica de Portugal." },
      fr: { name: "Eau Gazeuse Pedras", description: "Eau minérale naturelle gazeuse Pedras Salgadas, 75cl. L'eau gazeuse la plus emblématique du Portugal." },
    },
    price: 3.0, image_url: `${UNS}1705413085032-77fec96871cf${fmt}`,
    allergens: [], calories: 0, proteins: 0, carbs: 0, fat: 0,
    is_available: true, is_featured: false, tags: ["sem álcool"],
    position: 5, created_at: new Date().toISOString(), updated_at: new Date().toISOString(),
  },
  {
    id: "dish-020", restaurant_id: "rest-001", category_id: "cat-005",
    name: "Espresso Duplo",
    description: "Blend exclusivo de grãos de origem única, tostagem média-escura. Servido com petit four da casa.",
    translations: {
      en: { name: "Double Espresso", description: "Exclusive blend of single-origin beans, medium-dark roast. Served with a house petit four." },
      es: { name: "Espresso Doble", description: "Blend exclusivo de granos de origen único, tostado medio-oscuro. Servido con petit four de la casa." },
      fr: { name: "Double Espresso", description: "Blend exclusif de grains d'origine unique, torréfaction mi-sombre. Servi avec un petit four maison." },
    },
    price: 2.5, image_url: `${UNS}1544145945-f90425340c7e${fmt}`,
    allergens: [], calories: 5, proteins: 0, carbs: 1, fat: 0,
    is_available: true, is_featured: false, tags: ["café", "sem álcool"],
    position: 6, created_at: new Date().toISOString(), updated_at: new Date().toISOString(),
  },
];
