import type { Restaurant, Category, Dish } from "@/types";

const UNS = "https://images.unsplash.com/photo-";
const fmt = "?w=800&q=90&auto=format&fit=crop";

export const mockRestaurant: Restaurant = {
  id: "rest-001",
  slug: "casa-do-mar",
  name: "Casa do Mar",
  description:
    "Cozinha mediterrânica contemporânea com ingredientes frescos da costa portuguesa.",
  logo_url: undefined,
  cover_url: `${UNS}1414235077428-338989a2e8c0${fmt}`,
  address: "Rua do Ouro 12, Lisboa",
  phone: "+351 21 000 0000",
  cuisine_type: "Mediterrânica",
  primary_color: "#e6a81e",
  owner_id: "owner-001",
  is_active: true,
  created_at: new Date().toISOString(),
};

export const mockCategories: Category[] = [
  {
    id: "cat-001", restaurant_id: "rest-001", name: "Entradas", description: "Para começar bem", position: 1, created_at: new Date().toISOString(),
    translations: {
      en: { name: "Starters", description: "The perfect start" },
      es: { name: "Entrantes", description: "El comienzo perfecto" },
      fr: { name: "Entrées", description: "Pour bien commencer" },
    },
  },
  {
    id: "cat-002", restaurant_id: "rest-001", name: "Pratos Principais", description: "O coração da nossa cozinha", position: 2, created_at: new Date().toISOString(),
    translations: {
      en: { name: "Main Courses", description: "The heart of our kitchen" },
      es: { name: "Platos Principales", description: "El corazón de nuestra cocina" },
      fr: { name: "Plats Principaux", description: "Le cœur de notre cuisine" },
    },
  },
  {
    id: "cat-003", restaurant_id: "rest-001", name: "Sobremesas", description: "O final perfeito", position: 3, created_at: new Date().toISOString(),
    translations: {
      en: { name: "Desserts", description: "The perfect ending" },
      es: { name: "Postres", description: "El final perfecto" },
      fr: { name: "Desserts", description: "La conclusion parfaite" },
    },
  },
  {
    id: "cat-004", restaurant_id: "rest-001", name: "Vinhos", description: "Seleção de vinhos portugueses", position: 4, created_at: new Date().toISOString(),
    translations: {
      en: { name: "Wines", description: "Selection of Portuguese wines" },
      es: { name: "Vinos", description: "Selección de vinos portugueses" },
      fr: { name: "Vins", description: "Sélection de vins portugais" },
    },
  },
  {
    id: "cat-005", restaurant_id: "rest-001", name: "Bebidas", description: "Cervejas, cocktails e sumos", position: 5, created_at: new Date().toISOString(),
    translations: {
      en: { name: "Beverages", description: "Beers, cocktails and juices" },
      es: { name: "Bebidas", description: "Cervezas, cócteles y zumos" },
      fr: { name: "Boissons", description: "Bières, cocktails et jus" },
    },
  },
];

export const mockDishes: Dish[] = [
  // — Entradas —
  {
    id: "dish-001", restaurant_id: "rest-001", category_id: "cat-001",
    name: "Polvo à Lagareiro",
    description: "Polvo assado no forno com azeite extra virgem, alho confitado e batata a murro com ervas aromáticas.",
    translations: {
      en: { name: "Octopus à Lagareiro", description: "Oven-roasted octopus with extra virgin olive oil, confit garlic and crushed potatoes with aromatic herbs." },
      es: { name: "Pulpo à Lagareiro", description: "Pulpo asado al horno con aceite de oliva virgen extra, ajo confitado y patatas machacadas con hierbas aromáticas." },
      fr: { name: "Pieuvre à Lagareiro", description: "Pieuvre rôtie au four avec huile d'olive extra vierge, ail confit et pommes de terre écrasées aux herbes aromatiques." },
    },
    price: 14.5, image_url: `${UNS}1540189549336-e6e99c3679fe${fmt}`,
    allergens: ["moluscos"], calories: 320, proteins: 28, carbs: 18, fat: 14,
    is_available: true, is_featured: true, tags: ["popular", "sem-glúten"],
    position: 1, created_at: new Date().toISOString(), updated_at: new Date().toISOString(),
  },
  {
    id: "dish-002", restaurant_id: "rest-001", category_id: "cat-001",
    name: "Alheira de Caça com Ovo",
    description: "Alheira tradicional transmontana grelhada, servida com ovo escalfado e legumes salteados.",
    translations: {
      en: { name: "Game Sausage with Egg", description: "Traditional Transmontana game sausage grilled, served with a poached egg and sautéed vegetables." },
      es: { name: "Alheira de Caza con Huevo", description: "Alheira tradicional transmontana a la plancha, servida con huevo escalfado y verduras salteadas." },
      fr: { name: "Saucisse de Gibier à l'Oeuf", description: "Alheira traditionnelle transmontane grillée, servie avec un œuf poché et des légumes sautés." },
    },
    price: 10.5, image_url: `${UNS}1482049016688-2d3e1b311543${fmt}`,
    allergens: ["gluten", "ovos"], calories: 480, proteins: 22, carbs: 32, fat: 28,
    is_available: true, is_featured: false, tags: [],
    position: 2, created_at: new Date().toISOString(), updated_at: new Date().toISOString(),
  },
  {
    id: "dish-003", restaurant_id: "rest-001", category_id: "cat-001",
    name: "Creme de Mariscos",
    description: "Sopa cremosa de mariscos com natas, açafrão e torradas de pão de milho.",
    translations: {
      en: { name: "Seafood Bisque", description: "Creamy seafood bisque with cream, saffron and cornbread croutons." },
      es: { name: "Crema de Mariscos", description: "Sopa cremosa de mariscos con nata, azafrán y tostadas de pan de maíz." },
      fr: { name: "Bisque de Fruits de Mer", description: "Bisque crémeuse de fruits de mer avec crème, safran et croûtons de pain de maïs." },
    },
    price: 9.0, image_url: `${UNS}1547592166-23ac45744acd${fmt}`,
    allergens: ["crustaceos", "moluscos", "leite", "gluten"], calories: 380, proteins: 18, carbs: 22, fat: 24,
    is_available: true, is_featured: false, tags: [],
    position: 3, created_at: new Date().toISOString(), updated_at: new Date().toISOString(),
  },
  // — Pratos Principais —
  {
    id: "dish-004", restaurant_id: "rest-001", category_id: "cat-002",
    name: "Bacalhau à Brás",
    description: "Bacalhau desfiado com ovos mexidos, batata palha frita, azeitonas pretas e salsa fresca.",
    translations: {
      en: { name: "Bacalhau à Brás", description: "Shredded salt cod with scrambled eggs, crispy straw potatoes, black olives and fresh parsley." },
      es: { name: "Bacalao à Brás", description: "Bacalao desmigado con huevos revueltos, patatas paja fritas, aceitunas negras y perejil fresco." },
      fr: { name: "Morue à la Brás", description: "Morue effilée avec œufs brouillés, pommes pailles croustillantes, olives noires et persil frais." },
    },
    price: 22.0, image_url: `${UNS}1764333580740-b327847301b1${fmt}`,
    allergens: ["peixe", "ovos"], calories: 620, proteins: 42, carbs: 38, fat: 32,
    is_available: true, is_featured: false, tags: ["popular", "tradicional"],
    position: 1, created_at: new Date().toISOString(), updated_at: new Date().toISOString(),
  },
  {
    id: "dish-005", restaurant_id: "rest-001", category_id: "cat-002",
    name: "Robalo Grelhado",
    description: "Robalo inteiro do Atlântico grelhado com limão, azeite aromatizado e legumes da época.",
    translations: {
      en: { name: "Grilled Sea Bass", description: "Whole Atlantic sea bass grilled with lemon, flavoured olive oil and seasonal vegetables." },
      es: { name: "Lubina a la Plancha", description: "Lubina entera del Atlántico a la plancha con limón, aceite aromatizado y verduras de temporada." },
      fr: { name: "Bar Grillé", description: "Bar entier de l'Atlantique grillé au citron, huile aromatisée et légumes de saison." },
    },
    price: 28.0, image_url: `${UNS}1519708227418-c8fd9a32b7a2${fmt}`,
    allergens: ["peixe"], calories: 520, proteins: 52, carbs: 8, fat: 28,
    is_available: true, is_featured: true, tags: ["saudável", "sem-glúten"],
    position: 2, created_at: new Date().toISOString(), updated_at: new Date().toISOString(),
  },
  {
    id: "dish-006", restaurant_id: "rest-001", category_id: "cat-002",
    name: "Secretos de Porco Preto",
    description: "Secretos de porco preto alentejano grelhados a carvão com migas de pão e cogumelos selvagens.",
    translations: {
      en: { name: "Black Pork Secreto", description: "Alentejo black pork secreto cuts charcoal-grilled with bread crumbs and wild mushrooms." },
      es: { name: "Secretos de Cerdo Negro", description: "Secretos de cerdo negro alentejano a la brasa con migas de pan y setas silvestres." },
      fr: { name: "Secreto de Porc Noir", description: "Secretos de porc noir alentejano grillés au charbon avec migas de pain et champignons sauvages." },
    },
    price: 24.0, image_url: `${UNS}1600891964092-4316c288032e${fmt}`,
    allergens: ["gluten"], calories: 680, proteins: 48, carbs: 28, fat: 38,
    is_available: true, is_featured: false, tags: ["sem-lactose"],
    position: 3, created_at: new Date().toISOString(), updated_at: new Date().toISOString(),
  },
  {
    id: "dish-007", restaurant_id: "rest-001", category_id: "cat-002",
    name: "Risotto de Gambas",
    description: "Risotto cremoso com gambas salteadas, parmesão, vinho branco e manjericão fresco.",
    translations: {
      en: { name: "Prawn Risotto", description: "Creamy risotto with sautéed prawns, parmesan, white wine and fresh basil." },
      es: { name: "Risotto de Gambas", description: "Risotto cremoso con gambas salteadas, parmesano, vino blanco y albahaca fresca." },
      fr: { name: "Risotto aux Crevettes", description: "Risotto crémeux avec crevettes sautées, parmesan, vin blanc et basilic frais." },
    },
    price: 19.5, image_url: `${UNS}1476124369491-e7addf5db371${fmt}`,
    allergens: ["crustaceos", "leite", "gluten"], calories: 580, proteins: 32, carbs: 58, fat: 22,
    is_available: true, is_featured: false, tags: [],
    position: 4, created_at: new Date().toISOString(), updated_at: new Date().toISOString(),
  },
  // — Sobremesas —
  {
    id: "dish-008", restaurant_id: "rest-001", category_id: "cat-003",
    name: "Pastel de Nata da Casa",
    description: "Pastel de nata artesanal com creme de baunilha, canela e açúcar em pó.",
    translations: {
      en: { name: "House Custard Tart", description: "Artisan custard tart with vanilla cream, cinnamon and icing sugar." },
      es: { name: "Pastel de Nata de la Casa", description: "Pastel de nata artesanal con crema de vainilla, canela y azúcar glas." },
      fr: { name: "Tarte à la Crème Maison", description: "Tarte à la crème artisanale avec crème à la vanille, cannelle et sucre glace." },
    },
    price: 4.5, image_url: `${UNS}1621303837174-89787a7d4729${fmt}`,
    allergens: ["gluten", "ovos", "leite"], calories: 285, proteins: 6, carbs: 38, fat: 12,
    is_available: true, is_featured: true, tags: ["popular"],
    position: 1, created_at: new Date().toISOString(), updated_at: new Date().toISOString(),
  },
  {
    id: "dish-009", restaurant_id: "rest-001", category_id: "cat-003",
    name: "Tarte de Amêndoa",
    description: "Tarte alentejana de amêndoa caramelizada com gelado de mel e lavanda.",
    translations: {
      en: { name: "Almond Tart", description: "Alentejo caramelised almond tart with honey and lavender ice cream." },
      es: { name: "Tarta de Almendra", description: "Tarta alentejana de almendra caramelizada con helado de miel y lavanda." },
      fr: { name: "Tarte aux Amandes", description: "Tarte alentejane à l'amande caramélisée avec glace au miel et lavande." },
    },
    price: 7.5, image_url: `${UNS}1519915028121-7d3463d20b13${fmt}`,
    allergens: ["gluten", "ovos", "leite", "frutos_casca"], calories: 420, proteins: 8, carbs: 52, fat: 22,
    is_available: true, is_featured: false, tags: [],
    position: 2, created_at: new Date().toISOString(), updated_at: new Date().toISOString(),
  },
  {
    id: "dish-010", restaurant_id: "rest-001", category_id: "cat-003",
    name: "Mousse de Chocolate Negro",
    description: "Mousse de chocolate negro 70% com flor de sal, praliné de avelã e folha de ouro.",
    translations: {
      en: { name: "Dark Chocolate Mousse", description: "70% dark chocolate mousse with fleur de sel, hazelnut praline and gold leaf." },
      es: { name: "Mousse de Chocolate Negro", description: "Mousse de chocolate negro 70% con flor de sal, praliné de avellana y hoja de oro." },
      fr: { name: "Mousse au Chocolat Noir", description: "Mousse au chocolat noir 70% avec fleur de sel, praliné noisette et feuille d'or." },
    },
    price: 8.0, image_url: `${UNS}1571877227200-a0d98ea607e9${fmt}`,
    allergens: ["ovos", "leite", "frutos_casca"], calories: 380, proteins: 5, carbs: 42, fat: 24,
    is_available: true, is_featured: false, tags: ["sem-glúten"],
    position: 3, created_at: new Date().toISOString(), updated_at: new Date().toISOString(),
  },
  // — Vinhos —
  {
    id: "dish-011", restaurant_id: "rest-001", category_id: "cat-004",
    name: "Quinta do Crasto Reserva Tinto",
    description: "Douro DOC 2021. Lote de Touriga Nacional e Touriga Franca com estágio em carvalho francês. Notas de frutos negros, especiarias e tosta.",
    translations: {
      en: { name: "Quinta do Crasto Reserva Red", description: "Douro DOC 2021. Blend of Touriga Nacional and Touriga Franca aged in French oak. Notes of dark fruit, spices and toast." },
      es: { name: "Quinta do Crasto Reserva Tinto", description: "Douro DOC 2021. Mezcla de Touriga Nacional y Touriga Franca con crianza en roble francés. Notas de frutos negros, especias y tostado." },
      fr: { name: "Quinta do Crasto Reserva Rouge", description: "Douro DOC 2021. Assemblage de Touriga Nacional et Touriga Franca élevé en chêne français. Notes de fruits noirs, épices et toast." },
    },
    price: 38.0, image_url: `${UNS}1553361371-9b22f78e8b1d${fmt}`,
    allergens: ["sulfitos"], calories: undefined, proteins: undefined, carbs: undefined, fat: undefined,
    is_available: true, is_featured: true, tags: ["tinto", "Douro"],
    position: 1, created_at: new Date().toISOString(), updated_at: new Date().toISOString(),
  },
  {
    id: "dish-012", restaurant_id: "rest-001", category_id: "cat-004",
    name: "Anselmo Mendes Alvarinho",
    description: "Vinho Verde DOC 2023. Alvarinho a 100% das encostas de Monção. Fresco, cítrico, com acidez vibrante e final mineral.",
    translations: {
      en: { name: "Anselmo Mendes Alvarinho", description: "Vinho Verde DOC 2023. 100% Alvarinho from the slopes of Monção. Fresh, citrusy, with vibrant acidity and a mineral finish." },
      es: { name: "Anselmo Mendes Alvarinho", description: "Vinho Verde DOC 2023. Alvarinho al 100% de las laderas de Monção. Fresco, cítrico, con acidez vibrante y final mineral." },
      fr: { name: "Anselmo Mendes Alvarinho", description: "Vinho Verde DOC 2023. Alvarinho à 100% des coteaux de Monção. Frais, citronné, avec une acidité vibrante et une finale minérale." },
    },
    price: 28.0, image_url: `${UNS}1682071308366-1d098905b498${fmt}`,
    allergens: ["sulfitos"], calories: undefined, proteins: undefined, carbs: undefined, fat: undefined,
    is_available: true, is_featured: false, tags: ["branco", "Vinho Verde"],
    position: 2, created_at: new Date().toISOString(), updated_at: new Date().toISOString(),
  },
  {
    id: "dish-013", restaurant_id: "rest-001", category_id: "cat-004",
    name: "Esporão Reserva Branco",
    description: "Alentejo DOC 2022. Blend de Antão Vaz e Arinto com fermentação parcial em barrica. Cremoso, com notas de frutos tropicais e baunilha.",
    translations: {
      en: { name: "Esporão Reserva White", description: "Alentejo DOC 2022. Blend of Antão Vaz and Arinto with partial barrel fermentation. Creamy, with notes of tropical fruits and vanilla." },
      es: { name: "Esporão Reserva Blanco", description: "Alentejo DOC 2022. Mezcla de Antão Vaz y Arinto con fermentación parcial en barrica. Cremoso, con notas de frutas tropicales y vainilla." },
      fr: { name: "Esporão Reserva Blanc", description: "Alentejo DOC 2022. Assemblage d'Antão Vaz et Arinto avec fermentation partielle en barrique. Crémeux, avec des notes de fruits tropicaux et vanille." },
    },
    price: 32.0, image_url: `${UNS}1474506654191-f7d09ec90b52${fmt}`,
    allergens: ["sulfitos"], calories: undefined, proteins: undefined, carbs: undefined, fat: undefined,
    is_available: true, is_featured: false, tags: ["branco", "Alentejo"],
    position: 3, created_at: new Date().toISOString(), updated_at: new Date().toISOString(),
  },
  {
    id: "dish-014", restaurant_id: "rest-001", category_id: "cat-004",
    name: "Niepoort Nat'Cool Rosé",
    description: "Douro 2023. Rosé leve e refrescante, cor salmão, aromas de framboesa e flor de rosa. Perfeito para os meses quentes.",
    translations: {
      en: { name: "Niepoort Nat'Cool Rosé", description: "Douro 2023. Light and refreshing rosé, salmon colour, aromas of raspberry and rose blossom. Perfect for warm months." },
      es: { name: "Niepoort Nat'Cool Rosado", description: "Douro 2023. Rosado ligero y refrescante, color salmón, aromas de frambuesa y flor de rosa. Perfecto para los meses cálidos." },
      fr: { name: "Niepoort Nat'Cool Rosé", description: "Douro 2023. Rosé léger et rafraîchissant, couleur saumon, arômes de framboise et de fleur de rose. Parfait pour les mois chauds." },
    },
    price: 24.0, image_url: `${UNS}1622119396095-378684e4bfa8${fmt}`,
    allergens: ["sulfitos"], calories: undefined, proteins: undefined, carbs: undefined, fat: undefined,
    is_available: true, is_featured: false, tags: ["rosé", "Douro"],
    position: 4, created_at: new Date().toISOString(), updated_at: new Date().toISOString(),
  },
  // — Bebidas —
  {
    id: "dish-015", restaurant_id: "rest-001", category_id: "cat-005",
    name: "Gin Tónico da Casa",
    description: "Gin Hendrick's com tónica premium Fever-Tree, pepino, zimbro e rodela de limão. Servido em copo de balão com gelo.",
    translations: {
      en: { name: "House Gin & Tonic", description: "Hendrick's Gin with premium Fever-Tree tonic, cucumber, juniper and a lemon slice. Served in a balloon glass with ice." },
      es: { name: "Gin Tónico de la Casa", description: "Gin Hendrick's con tónica premium Fever-Tree, pepino, enebro y rodaja de limón. Servido en copa globo con hielo." },
      fr: { name: "Gin Tonic Maison", description: "Gin Hendrick's avec tonic premium Fever-Tree, concombre, genièvre et rondelle de citron. Servi dans un verre ballon avec glace." },
    },
    price: 12.0, image_url: `${UNS}1563227812-0ea4c22e6cc8${fmt}`,
    allergens: [], calories: 180, proteins: 0, carbs: 14, fat: 0,
    is_available: true, is_featured: false, tags: ["cocktail", "com álcool"],
    position: 1, created_at: new Date().toISOString(), updated_at: new Date().toISOString(),
  },
  {
    id: "dish-016", restaurant_id: "rest-001", category_id: "cat-005",
    name: "Aperol Spritz",
    description: "Aperol, Prosecco DOC e água com gás com fatia de laranja. O clássico aperitivo italiano refrescante.",
    translations: {
      en: { name: "Aperol Spritz", description: "Aperol, Prosecco DOC and sparkling water with a slice of orange. The classic refreshing Italian aperitif." },
      es: { name: "Aperol Spritz", description: "Aperol, Prosecco DOC y agua con gas con rodaja de naranja. El clásico aperitivo italiano refrescante." },
      fr: { name: "Aperol Spritz", description: "Aperol, Prosecco DOC et eau gazeuse avec une tranche d'orange. Le classique apéritif italien rafraîchissant." },
    },
    price: 10.0, image_url: `${UNS}1585975776023-29a0dbc51407${fmt}`,
    allergens: ["sulfitos"], calories: 160, proteins: 0, carbs: 18, fat: 0,
    is_available: true, is_featured: false, tags: ["cocktail", "com álcool"],
    position: 2, created_at: new Date().toISOString(), updated_at: new Date().toISOString(),
  },
  {
    id: "dish-017", restaurant_id: "rest-001", category_id: "cat-005",
    name: "Cerveja Artesanal IPA",
    description: "IPA nacional produzida em Lisboa. Lúpulo intenso, aromas cítricos e final amargo equilibrado. 5.8% vol.",
    translations: {
      en: { name: "Craft IPA Beer", description: "National IPA brewed in Lisbon. Intense hops, citrus aromas and a balanced bitter finish. 5.8% vol." },
      es: { name: "Cerveza Artesanal IPA", description: "IPA nacional elaborada en Lisboa. Lúpulo intenso, aromas cítricos y final amargo equilibrado. 5.8% vol." },
      fr: { name: "Bière Artisanale IPA", description: "IPA nationale brassée à Lisbonne. Houblon intense, arômes citronnés et finale amère équilibrée. 5,8% vol." },
    },
    price: 5.5, image_url: `${UNS}1437418747212-8d9709afab22${fmt}`,
    allergens: ["gluten"], calories: 210, proteins: 2, carbs: 18, fat: 0,
    is_available: true, is_featured: false, tags: ["cerveja", "com álcool"],
    position: 3, created_at: new Date().toISOString(), updated_at: new Date().toISOString(),
  },
  {
    id: "dish-018", restaurant_id: "rest-001", category_id: "cat-005",
    name: "Limonada Fresca da Casa",
    description: "Limão espremido na hora, hortelã fresca, xarope de açúcar artesanal e água com gás. Refrescante e natural.",
    translations: {
      en: { name: "House Fresh Lemonade", description: "Freshly squeezed lemon, fresh mint, artisan sugar syrup and sparkling water. Refreshing and natural." },
      es: { name: "Limonada Fresca de la Casa", description: "Limón exprimido al momento, menta fresca, sirope de azúcar artesanal y agua con gas. Refrescante y natural." },
      fr: { name: "Limonade Fraîche Maison", description: "Citron pressé frais, menthe fraîche, sirop de sucre artisanal et eau gazeuse. Rafraîchissant et naturel." },
    },
    price: 4.5, image_url: `${UNS}1513558161293-cdaf765ed2fd${fmt}`,
    allergens: [], calories: 95, proteins: 0, carbs: 22, fat: 0,
    is_available: true, is_featured: false, tags: ["sem álcool"],
    position: 4, created_at: new Date().toISOString(), updated_at: new Date().toISOString(),
  },
  {
    id: "dish-019", restaurant_id: "rest-001", category_id: "cat-005",
    name: "Água com Gás Pedras",
    description: "Água mineral natural com gás Pedras Salgadas, 75cl. A água gasificada mais icónica de Portugal.",
    translations: {
      en: { name: "Pedras Sparkling Water", description: "Pedras Salgadas natural sparkling mineral water, 75cl. Portugal's most iconic sparkling water." },
      es: { name: "Agua con Gas Pedras", description: "Agua mineral natural con gas Pedras Salgadas, 75cl. El agua con gas más icónica de Portugal." },
      fr: { name: "Eau Gazeuse Pedras", description: "Eau minérale naturelle gazeuse Pedras Salgadas, 75cl. L'eau gazeuse la plus emblématique du Portugal." },
    },
    price: 3.0, image_url: `${UNS}1705413085032-77fec96871cf${fmt}`,
    allergens: [], calories: 0, proteins: 0, carbs: 0, fat: 0,
    is_available: true, is_featured: false, tags: ["sem álcool"],
    position: 5, created_at: new Date().toISOString(), updated_at: new Date().toISOString(),
  },
  {
    id: "dish-020", restaurant_id: "rest-001", category_id: "cat-005",
    name: "Espresso Duplo",
    description: "Blend exclusivo de grãos de origem única, tostagem média-escura. Servido com petit four da casa.",
    translations: {
      en: { name: "Double Espresso", description: "Exclusive blend of single-origin beans, medium-dark roast. Served with a house petit four." },
      es: { name: "Espresso Doble", description: "Blend exclusivo de granos de origen único, tostado medio-oscuro. Servido con petit four de la casa." },
      fr: { name: "Double Espresso", description: "Blend exclusif de grains d'origine unique, torréfaction mi-sombre. Servi avec un petit four maison." },
    },
    price: 2.5, image_url: `${UNS}1544145945-f90425340c7e${fmt}`,
    allergens: [], calories: 5, proteins: 0, carbs: 1, fat: 0,
    is_available: true, is_featured: false, tags: ["café", "sem álcool"],
    position: 6, created_at: new Date().toISOString(), updated_at: new Date().toISOString(),
  },
];
